### ISSUE TITLE
The server is not loading the Mods

### ISSUE THREAD

**Issue by NicMan37** [JACOBSMILE/tmodloader1.4#20]
Hi,
i'm having an  issue deploying the container with mods

i'm using portainer to managing the stack. above the compose file

```
version: "3.9"

volumes:
  data:
  workshop:

networks:
  default:
    external: true
    name: game_network

services:
  tmodloader:
    image: jacobsmile/tmodloader1.4
    container_name: TModLoader
    ports:
      - 7777:7777
    expose:
      - 7777
    environment:
      #Boss Checklist, Recipe Browser, Calamity Mod, Calamity Mod Music, Magic Storage, Calamity's Vanities, Thorium Mod, Wing Slot Extra, Which Mod Is This From? (WMITF), Max Stack Plus Extra, Smarter Cursor, Loot Beams, Compare Item Stats, Shop Expander
      TMOD_AUTODOWNLOAD: 2669644269,2619954303,2824688072,2824688266,2563309347,2824688804,2909886416,2597324266,2563851005,2562915378,2877850919,2847872897,2576847291,2828370879
      #Boss Checklist, Recipe Browser, Calamity Mod, Calamity Mod Music, Magic Storage, Calamity's Vanities, Thorium Mod, Wing Slot Extra, Which Mod Is This From? (WMITF), Max Stack Plus Extra, Smarter Cursor, Loot Beams, Compare Item Stats, Shop Expander
      TMOD_ENABLEDMODS: 2669644269,2619954303,2824688072,2824688266,2563309347,2824688804,2909886416,2597324266,2563851005,2562915378,2877850919,2847872897,2576847291,2828370879
      # Shutdown Message and Autosave Interval (In Minutes)
      TMOD_SHUTDOWN_MESSAGE: "Shutting Down"
      TMOD_AUTOSAVE_INTERVAL: 10
      # Server Settings
      TMOD_MOTD: "Welcome!"
      TMOD_PASS: password
      TMOD_MAXPLAYERS: 10
      # The following world settings are only used when generating a new world.
      TMOD_WORLDNAME: World
      TMOD_WORLDSIZE: 3
      TMOD_WORLDSEED: ""
      TMOD_DIFFICULTY: 2
      TMOD_SECURE: 1
      TMOD_NPCSTREAM: 60

    volumes:
      - data:/home/terraria/.local/share/Terraria/tModLoader/Worlds
      - workshop:/home/terraria/terraria-server/workshop-mods
```

it seems it doesn't downloading the mods to the `/home/terraria/terraria-server/workshop-mods` folder
![image](https://user-images.githubusercontent.com/17047602/236784438-a4707dab-9c3c-420a-942a-9aa99121ec29.png)
in the logs i found this 
`Downloaded item 2669644269 to "/home/terraria/Steam/steamapps/workshop/content/1281930/2669644269"`

```
[SYSTEM] Enabling 2669644269...
ls: cannot access '/home/terraria/terraria-server/workshop-mods/steamapps/workshop/content/1281930/2669644269/*/': No such file or directory
```

Best Regards
Manuel
